[package]
name = "auction"
version = "0.1.0"
edition = "2024"

[dependencies]
scylla = "0.12"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "uuid"] }
async-trait = "0.1"
anyhow = "1"
axum = { version = "0.7", features = ["ws"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
dashmap = "5.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }